### PR TITLE
add support for  X-Forward-* Headers

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
Hi I've added a flag which turns on the xfwd option for http-proxy. With that option the proxied requests will get additional X-Forward-\* Headers. They are necessary to proper implement a revere proxy scenario.

Thx for the great tool.

### CODE REVIEW

**Comment by indexzero** [comment]
Thanks for your contribution. Need test coverage for this new feature.

**Comment by thornjad** [comment]
@johann-sonntagbauer if you're still interested in this PR, could you rebase onto the current master and add some test coverage for this option?

**Comment by johann-sonntagbauer** [comment]
@thornjad I am currently pretty busy. So it would take some time. If that is ok for you.

**Comment by thornjad** [comment]
No problem, you're not on a deadline! If anyone else wants to take this on in the meantime that could make it move faster

**Comment by thornjad** [comment]
Closing since the remote branch has been deleted

**Pull request closed without merging**
