### PR TITLE
feat: auto gen self signed cert

### LINKED ISSUE #402: Make https DX better
Hey,
first of all great project! 

I would recommend one improvement. It would be nice if `http-server -S path` would generate automatically some dummy ssl certs for me so i don't need to do it by myself. `webpack-dev-server` does it and it's great. Otherwise I need to generate them with something like (this at least should be part of the readme):

`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`

Best!

### PR DESCRIPTION
**Pull request by wood1986**
**Please ensure that your pull request fulfills these requirements:**
- [x] The pull request is being made against the `master` branch
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the purpose of this pull request? (bug fix, enhancement, new feature,...)**
automatically generate a self-signed certificate. fix #402 and #431

**What changes did you make?**
I only make the change to bin/http-server

**Provide some example code that this change will affect, if applicable:**

**Is there anything you'd like reviewers to focus on?**

**Please provide testing instructions, if applicable:**
I do not know how to add test to the bin/http-server

### CODE REVIEW

**Comment by wood1986** [comment]
I hope you guys can take my PR. Thanks

**Comment by thornjad** [comment]
I'm very hesitant about automatically creating certificates, that shouldn't really be the responsibility of a server.

Also, it looks like this PR makes http-server always create a certificate if there isn't one already. What if a user doesn't want to generate a certificate?

**Comment by wood1986** [comment]
>Also, it looks like this PR makes http-server always create a certificate if there isn't one already. What if a user doesn't want to generate a certificate?

https://github.com/wood1986/http-server/blob/7b670ed24d0b48bdd8cd05d4a824e174e3292025/bin/http-server#L140

has already respected that. If people passed a cert and it is valid, I will auto generate it. If they do not want to generate it and use their own cert, L140 will not go in

**Comment by thornjad** [comment]
Unless @BigBlueHat or @indexzero disagree with me, I'm going to say this is out-of-scope, i.e. not something http-server should be doing.

**Comment by AJLoveChina** [comment]
@wood1986  
you can try this :  https://github.com/AJLoveChina/http-server-v2

**Comment by BigBlueHat** [comment]
@AJLoveChina thanks for building that for folks who want it. However, could you rename the project to something that doesn't imply that it's part of this project? Thanks!

**Comment by AJLoveChina** [comment]
> @AJLoveChina thanks for building that for folks who want it. However, could you rename the project to something that doesn't imply that it's part of this project? Thanks!

wlc and that's fine, new name is : https://github.com/AJLoveChina/hs2

**Comment by BigBlueHat** [comment]
Thanks, @AJLoveChina!

**Pull request closed without merging**
