### PR TITLE
support custom mime-type(s) via .types file

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This is my take on fixing #35, if [my upstream PR](https://github.com/jfhbrook/node-ecstatic/pull/143) lands.
I need some help though. I can't figure out how to test the feature with vows. If I start http-server, I can request files with custom mime-types but no matter what I do in [http-server-test.js](https://github.com/dotnetCarpenter/http-server/blob/ecstatic/test/http-server-test.js#L169), I get an ECONNREFUSED. I'm pretty sure it's a race condition but I can't figure out how to fix it.

Any ideas?

### CODE REVIEW

**Comment by indexzero** [comment]
Too bad you abandoned writing tests for this. I'm going to leave it open in case anyone feels compelled to write them (including myself).

**Comment by dotnetCarpenter** [comment]
I might give it a shot next time I got spare time on my hands. Seems like the repo is busy at the moment - that's always encouraging.

**Comment by BigBlueHat** [comment]
@dotnetCarpenter don't suppose you're still around and interested in revisiting this PR per chance? :grin:

**Comment by dotnetCarpenter** [comment]
My issue was only with the Vows test. The PR was working great but somehow
the timing was off with Vows. Maybe it's fixed by now. Unfortunately, I
don't have time in the foreseeable future to check it. But give it shot! :)

**Comment by BigBlueHat** [comment]
Thanks for getting this started @dotnetCarpenter! Given that the ecstatic supports it https://github.com/jfhbrook/node-ecstatic#optsmimetypes we should revisit this sometime.

I'll leave this open to track other variations or forks of this work.

Thanks again @dotnetCarpenter!

**Comment by thornjad** [comment]
Should be implemented by #693, please open a new issue/PR if this is not the case

**Pull request closed without merging**
