### PR TITLE
regenerate package-lock.json

### PR DESCRIPTION
**Pull request by dotlambda**
Otherwise installation fails with
```
npm ERR! request to https://registry.npmjs.org/url-join failed: cache mode is 'only-if-cached' but no cached response is available.
```

##### Contributor checklist

- [ ] Provide tests for the changes (unless documentation-only)
- [ ] Documented any new features, CLI switches, etc. (if applicable)
    - [ ] Server `--help` output
    - [ ] README.md
    - [ ] doc/http-server.1 (use the same format as other entries)
- [x] The pull request is being made against the `master` branch

##### Maintainer checklist

- [ ] Assign a version triage tag
- [ ] Approve tests if applicable

### CODE REVIEW

**Comment by KernelDeimos** [comment]
Hello, I'm not currently able to reproduce this. That said it's been a while since this was opened - are you still able to reproduce this issue?

**Comment by dotlambda** [comment]
Yes, same issue on master:
```
npm error request to https://registry.npmjs.org/yallist failed: cache mode is 'only-if-cached' but no cached response is available.
```
I'm building with Nix's `buildNpmPackage` which uses `npm config offline true`.

**Comment by KernelDeimos** [comment]
What causes this? I don't use NixOS so I'm not sure how buildNpmPackage works. Is it a hash that's stale, or do some packages need to be at specific versions which are in some Nix-specific repos, or is it something else?

**Comment by KernelDeimos** [comment]
Closing due to no response, feel free to re-open if this issue persists.

**Pull request closed without merging**
