### PR TITLE
Dockerize http-server

### LINKED ISSUE #724: http-server dockerized
Hi @thornjad 
I have dockerized http-server, you can find image [here](https://hub.docker.com/r/tozlu/http-server) and repository [here](/mtozlu/http-server-docker). You can add this to docs if you want.

Thank you for the awesome repo.

### PR DESCRIPTION
**Pull request by mtozlu**
Dockerization of http-server

##### Relevant issues

Closes #724 

##### Contributor checklist

- [ ] Provide tests for the changes (unless documentation-only)
- [x] Documented any new features, CLI switches, etc. (if applicable)
    - [ ] Server `--help` output
    - [x] README.md
    - [x] doc/http-server.1 (use the same format as other entries)
- [x] The pull request is being made against the `master` branch

##### Maintainer checklist

- [ ] Assign a version triage tag
- [ ] Approve tests if applicable

Maintainers will do the building, tagging and pushing docker images. 
These instructions are only for maintainers to release a new version in docker hub;

### Building and Tagging the Docker Image
- Make sure to checkout the desired version/branch before building docker image for that version
- Run `docker build -t {your-username}/http-server:{new-version} -t {your-username}/http-server:latest .` in project root folder.
*This builds and tags the docker image with "latest" tag and also with the version you provide.*
### Pushing the Docker Image
- After successful build, you can push all tags to your docker repository
- Push the version tag: `docker push {your-username}/http-server:{new-version}`
- Push the "latest" tag: `docker push {your-username}/http-server:latest`

Note: I already have the http-server images built in docker hub in my own repository (which is [tozlu/http-server](https://hub.docker.com/repository/docker/tozlu/http-server)), if you would like to maintain docker images in your own repository, please change README and the build/push scripts above to reflect your username for docker hub.

### CODE REVIEW

**Comment by gaby** [comment]
@mtozlu Have you try running the final bin with Google Distroless images?

`FROM gcr.io/distroless/nodejs:16`

**Comment by mtozlu** [comment]
@gaby No. But it looks cool. Should I switch to it? What are the benefits over alpine?

**Comment by gaby** [comment]
> @gaby No. But it looks cool. Should I switch to it? What are the benefits over alpine?

If it runs fine, I would say yes.

**Comment by indexzero** [comment]
Similar to #790

**Comment by KernelDeimos** [comment]
Resolved by e8a96d065affccc4fd16964881cf12acddecf226

**Comment by gaby** [comment]
@KernelDeimos I can submit a PR to add the GitHub workflow to publish the image here on GH. Github has the ghcr.io registry which is free.

**Comment by KernelDeimos** [comment]
> @KernelDeimos I can submit a PR to add the GitHub workflow to publish the image here on GH. Github has the ghcr.io registry which is free.

Yep, let's do it!

**Pull request closed without merging**
