### PR TITLE
Add `--base-dir` to cli options to specify base path

### PR DESCRIPTION
**Pull request by MaximSagan**
Rebased and update stale PR https://github.com/http-party/http-server/pull/294.
Fixes https://github.com/http-party/http-server/issues/139.

### CODE REVIEW

**Comment by Galileon-venta** [comment]
Is @thornjad the only one to merge on this project? Is there any realistic ETA for this to be contained in a new release?

**Comment by MaximSagan** [comment]
> Is @thornjad the only one to merge on this project? Is there any realistic ETA for this to be contained in a new release?

Yep, it's only @thornjad, and unfortunately he seems to have largely abandoned this project.

**Comment by cmoesel** [comment]
In case anyone is still keeping track, I'd love to see this feature merged in.

**Comment by KernelDeimos** [comment]
Preferring this over #294 because this is more recent and has fewer whitespace-only changes

**Comment by KernelDeimos** [comment]
I forgot GH would do a merge commit instead of rebasing when I did that... gross

**Comment by KernelDeimos** [comment]
The tests which didn't pass appear to be due to a race condition on port conflicts for test servers, so I'm considering this good to go - going to merge and re-test.

**Comment by kirill-konshin** [comment]
Looks like this PR has been merged, but there's no release, what is the likelihood that will be released any time soon?

**Pull request merged**
