### PR TITLE
add --overlay option

### PR DESCRIPTION
**Pull request by dashie**
Add the possibility to specify an optional --overlay folder, if the file to serve exists in this folder this file overlay the base file in the root folder

### CODE REVIEW

**Comment by BigBlueHat** [comment]
What's the use case?

**Comment by thornjad** [comment]
Would you be able to do this by serving the "overlay" directory and using the main directory as a proxy? Then the overlay directory would be checked first, and if it doesn't have a file, it goes the the proxy.

**Comment by dashie** [comment]
> Would you be able to do this by serving the "overlay" directory and using the main directory as a proxy? Then the overlay directory would be checked first, and if it doesn't have a file, it goes the the proxy.

Yes I know, but I don't want to run 2 processes and bind 2 ports.
But the behavior would be the same.

**Comment by thornjad** [comment]
I think this is out-of-scope for http-server, since the proxy option would have the same effect. Without a proxy, if a file isn't found, it's a 404 error.

This would be a good use case for a small independent package which uses the proxy method automatically, given a root and overlay directory.

**Pull request closed without merging**
