### PR TITLE
Support custom mime types (content-type)

### PR DESCRIPTION
**Pull request by 599316527**
Just pass the mimeTypes option to node-ecstatic.

### CODE REVIEW

**Comment by thornjad** [comment]
👍 lgtm

**Comment by Smilebags** [comment]
Why has this not been merged? Such a simple change which solves so many problems. I'll be hand-copying these changes so I can use http-server to serve wasm modules.

**Comment by nickolay** [comment]
Even with this patch I wasn't able to use wasm modules -- probably due to https://github.com/indexzero/http-server/issues/480 . As noted there, with ecstatic 4.0.0 wasm was served with the correct content-type out-of-the-box.

**Comment by J-Rojas** [comment]
@nickolay #565 solves the wasm problem along with supporting mime types.

**Comment by thornjad** [comment]
Closing in favor of #693, since we'll be able to support it directly

**Pull request closed without merging**
