### PR TITLE
Feature: add `--find-port` parameter

### PR DESCRIPTION
**Pull request by harttle**
Find a free port when the port given by `-p` is not available. Solves #363

### CODE REVIEW

**Comment by ahmetb** [comment]
I think this should be implemented as `-p 0` flag. See #386.

**Comment by BigBlueHat** [comment]
@harttle would you have time/interest in writing some tests for this new feature? The code looks good, and the use case you expressed in https://github.com/indexzero/http-server/issues/386#issuecomment-320376241 may not be that uncommon (i.e. wanting a port "above" a certain number). Thanks!

**Comment by harttle** [comment]
This should be sufficient, yet not complete. Since `bin/http-server` wasn't tested before, it's hard to do complete test for it. For instance, the stdout/stderr.

**Comment by thornjad** [comment]
Given the discussion in #386, would this feature maybe be better implemented as a `--base-port` which is the same as the default behavior of no `--port` given, but searching begins at `--base-port`?

My concern with the `-p XXXX --find-port` pattern is that the user is both specifying a port _and_ expecting that the port may end up something other than what is specified. I think it may be more clear if an error is thrown when the port the user wants is in use. Then if the user wants to search for a port, they _don't_ use `-p` and may optionally determine the base port to start at.

@BigBlueHat @harttle @ahmetb any thoughts on a `--base-port` approach?

**Comment by sumitparakh** [comment]
What is the status of this PR?

**Comment by harttle** [comment]
Sorry I forgot this for a white and deleted that forked repo unexpectedly, I tried and could not restore that commit which is needed to continue patching this pull request. It's confirmed by [this question from stackexchange](https://softwareengineering.stackexchange.com/questions/61577/should-i-keep-my-github-forked-repositories-around-forever). If that's the way, we should open another PR for #386 and this should be closed. @thornjad

**Comment by sumitparakh** [comment]
Hi @harttle @thornjad . Would you mind if i try this?

**Comment by thornjad** [comment]
Closing since the fork is gone, and since we have #544

**Pull request closed without merging**
