### PR TITLE
proxy-pass option to avoid changing Host header

### PR DESCRIPTION
**Pull request by developit**
This adds a `proxy-pass` boolean option, which prevents the proxy from changing the origin of the host header to the target URL.

See `changeOrigin` option here: https://github.com/nodejitsu/node-http-proxy#options

### CODE REVIEW

**Comment by 0xR** [comment]
This is actually quite a old PR. I need this functionality as well. Did you find a workaround by now? @developit

**Comment by angelkenneth** [comment]
I had to copy and paste the `bin/http-server` and `lib/http-server.js` files to my own project just to i can set `changeOrigin: true`.

Still hoping this will be merged.

**Comment by fabioimpe** [comment]
@indexzero Please I this this functionality too, is there any chance too see this PR merged?

Thank you

**Comment by thornjad** [comment]
This looks reasonably straightforward and useful! However there are some merge conflicts which need to be resolved before this can move forward, @developit could you take a look at those?

**Comment by thornjad** [comment]
Given the variety of options available in http-proxy, this may be better implemented with the approach of passing through options to http-proxy itself in #459, what do you think?

**Comment by thornjad** [comment]
Closing in favor of #495

**Pull request closed without merging**
