### PR TITLE
feat(lib): Add the content encoding entity header gzip

### PR DESCRIPTION
**Pull request by NastyZ98**
This feature add the following:

- Addition of content-encoding "gzip" when a compressed file is requested

### CODE REVIEW

**Comment by msidhoum** [comment]
+1

**Comment by thornjad** [comment]
@NastyZ98 this should already be happening, have you experienced the Content-Encoding not being set correctly?

**Comment by thornjad** [comment]
Would you mind trying out the same thing using the current `master` branch? If it still isn't working, could you comment with the errors you're seeing and a list (or screenshot) of the headers that _are_ being sent? This may actually be a bug in `ecstatic`

**Comment by thornjad** [comment]
Closed since the branch for this PR has been deleted

**Pull request closed without merging**
