### PR TITLE
Send Accept-Ranges: bytes with every response

### PR DESCRIPTION
**Pull request by boramalper**
**Please ensure that your pull request fulfills these requirements:**
- [x] The pull request is being made against the `master` branch
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the purpose of this pull request? (bug fix, enhancement, new feature,...)**

Enhancement

**What changes did you make?**

Now `Accept-Ranges: bytes` header is sent with every response by default.

**Provide some example code that this change will affect, if applicable:**

N/A

**Is there anything you'd like reviewers to focus on?**

I think sending `Accept-Ranges: bytes` with every response is pretty benign, but surely the behaviour of some programs might be affected with this header (*i.e.* they might try to stream instead of downloading the whole file). If this is a concern, a new command-line flag can be added.

**Please provide testing instructions, if applicable:**

N/A

### CODE REVIEW

**Comment by thornjad** [comment]
What does this header mean for the client? What does it do?

**Comment by boramalper** [comment]
@thornjad See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges

**Comment by thornjad** [comment]
Would this fix #257?

**Comment by boramalper** [comment]
Sorry I no longer have the repository on my computer (removed it during a migration). It's a trivial change, so please feel free to go ahead and implement it yourself (without giving "credit"). =)

**Comment by thornjad** [comment]
Okay, sure I'll take over this PR!

**Comment by thornjad** [comment]
Presuming the tests pass, I'll approve this PR; thanks for your addition! I made a couple changes to your fork directly so we'll keep history and credit steady.

**Comment by boramalper** [comment]
Thanks! <3

**Pull request merged**
